<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\DataCollection.Core\DataCollection.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="GitHub.Octokit.SDK" />
    <PackageReference Include="HtmlAgilityPack" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Refit.HttpClientFactory" />
    <PackageReference Include="System.Threading.RateLimiting" />
    <PackageReference Include="OpenAI" />
    <PackageReference Include="OpenAI-DotNet.Json.Schema" />
  </ItemGroup>
  <Target BeforeTargets="CoreCompile" Name="GenerateBuildConstants">
    <PropertyGroup>
      <BuildConstantsFile>
				$(IntermediateOutputPath)\generated\MSBuildInject\BuildConstants.g.cs
			</BuildConstantsFile>
    </PropertyGroup>
    <ItemGroup>
      <BuildConstantsContent Include="namespace $(RootNamespace) %3B" />
      <BuildConstantsContent Include="public static class BuildConstants {" />
      <BuildConstantsContent Include="public const string SolutionDirectory = @&quot;$(SolutionDir)&quot;%3B" />
      <BuildConstantsContent Include="}" />
      <Compile Include="$(BuildConstantsFile)" />
    </ItemGroup>
    <WriteLinesToFile
      File="$(BuildConstantsFile)"
      Lines="@(BuildConstantsContent)"
      Overwrite="true"
    />
  </Target>
  <Target BeforeTargets="CoreCompile" Name="GenerateJsonSchema">
    <PropertyGroup>
      <JsonSchemaFile>
				$(IntermediateOutputPath)\generated\MSBuildInject\JsonSchema.g.cs
			</JsonSchemaFile>
    </PropertyGroup>
    <ItemGroup>
      <JsonSchemaContent Include="namespace $(RootNamespace) %3B" />
      <JsonSchemaContent Include="public static class JsonSchema {" />
      <JsonSchemaContent Include="public const string SolutionDirectory = @&quot;$(SolutionDir)&quot;%3B" />
      <JsonSchemaContent Include="}" />
      <Compile Include="$(JsonSchemaFile)" />
    </ItemGroup>
    <WriteLinesToFile File="$(JsonSchemaFile)" Lines="@(JsonSchemaContent)" Overwrite="true" />
  </Target>
</Project>
