<Project>
  <ItemGroup>
    <Compile Remove="build\**" />
    <Content Remove="build\**" />
    <EmbeddedResource Remove="build\**" />
    <None Remove="build\**" />
    <TrimmerRootDescriptor
      Include="TrimmerRoot.xml"
      Condition="Exists('TrimmerRoot.xml') and '$(PublishAot)' == 'true'"
    />
  </ItemGroup>
  <ItemGroup>
    <!-- Programming -->
    <PackageReference Include="morelinq" />
    <PackageReference Include="Enums.NET" />
    <PackageReference Include="AspectInjector" />
    <!-- Logging -->
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Settings.Configuration" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Enrichers.Environment" />
    <PackageReference
      Condition="'$(UsingMicrosoftNETSdkWeb)' == 'True'"
      Include="Serilog.AspNetCore"
    />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>
</Project>
