<Project>
  <Import
    Condition="Exists('$(MSBuildProjectDirectory)\obj\$(MSBuildProjectFile).EntityFrameworkCore.targets')"
    Project="$(MSBuildProjectDirectory)\obj\$(MSBuildProjectFile).EntityFrameworkCore.targets"
  />
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>
      true
    </CentralPackageTransitivePinningEnabled>
    <DotNetPreviewVersion>10.0.0-preview.7.25368.102</DotNetPreviewVersion>
  </PropertyGroup>
  <ItemGroup>
    <!-- Functional programming -->
    <PackageVersion Include="AspectInjector" Version="2.8.2" />
    <PackageVersion Include="morelinq" Version="4.4.0" />
    <PackageVersion Include="Enums.NET" Version="5.0.0" />
    <!-- Data -->
    <PackageVersion Include="HtmlAgilityPack" Version="1.12.2" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageVersion Include="OpenAI" Version="2.2.0-beta.4" />
    <PackageVersion Include="LarchSys.OpenAi.JsonSchema" Version="0.3.0" />
    <PackageVersion Include="NJsonSchema" Version="11.3.2" />
    <PackageVersion Include="Refit.HttpClientFactory" Version="8.0.0" />
    <PackageVersion Include="System.Threading.RateLimiting" Version="$(DotNetPreviewVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="$(DotNetPreviewVersion)" />
    <!-- Entity Framework -->
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="$(DotNetPreviewVersion)" />
    <PackageVersion
      Include="Microsoft.EntityFrameworkCore.Sqlite"
      Version="$(DotNetPreviewVersion)"
    />
    <PackageVersion
      Include="Microsoft.EntityFrameworkCore.Design"
      Version="$(DotNetPreviewVersion)"
    />
    <!-- Hosting -->
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="$(DotNetPreviewVersion)" />
    <PackageVersion
      Include="Microsoft.Extensions.Configuration.EnvironmentVariables"
      Version="$(DotNetPreviewVersion)"
    />
    <PackageVersion
      Include="Microsoft.Extensions.Configuration.Json"
      Version="$(DotNetPreviewVersion)"
    />
    <!-- IDisposable -->
    <PackageVersion Include="Fody" Version="6.9.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>
        runtime; build; native; contentfiles; analyzers; buildtransitive
      </IncludeAssets>
    </PackageVersion>
    <PackageVersion Include="Janitor.fody" Version="1.9.0">
      <PrivateAssets>all</PrivateAssets>
    </PackageVersion>
    <!-- Logging -->
    <PackageVersion Include="Serilog" Version="4.2.0" />
    <PackageVersion Include="Serilog.Extensions.Hosting" Version="9.0.0" />
    <PackageVersion Include="Serilog.Settings.Configuration" Version="9.0.0" />
    <PackageVersion Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageVersion Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageVersion Include="Serilog.Enrichers.Environment" Version="3.0.1" />
    <PackageVersion Include="Serilog.AspNetCore" Version="8.0.3" />
    <PackageVersion
      Include="Microsoft.Extensions.Logging.Abstractions"
      Version="$(DotNetPreviewVersion)"
    />
    <PackageVersion Include="MinimalHttpLogger" Version="3.0.0" />
    <!-- Memory -->
    <PackageVersion Include="CommunityToolkit.HighPerformance" Version="8.4.0-preview2" />
    <!-- Testing -->
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageVersion Include="NUnit" Version="4.2.2" />
    <PackageVersion Include="NUnit3TestAdapter" Version="5.0.0-beta.5" />
    <PackageVersion Include="NUnit.Analyzers" Version="4.4.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>
        runtime; build; native; contentfiles; analyzers; buildtransitive
      </IncludeAssets>
    </PackageVersion>
    <PackageVersion Include="coverlet.collector" Version="6.0.2" />
    <PackageVersion Include="Moq" Version="4.20.72" />
    <!-- Console -->
    <PackageVersion Include="ConsoleAppFramework" Version="5.5.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageVersion>
    <PackageVersion Include="Spectre.Console" Version="0.50.0" />
    <!-- Foreign Language -->
    <PackageVersion Include="pythonnet" Version="3.0.5" />
    <!-- Semantic Kernel -->
    <PackageVersion Include="Microsoft.SemanticKernel" Version="1.60.0" />
    <PackageVersion Include="Microsoft.SemanticKernel.Connectors.OpenAI" Version="1.60.0" />
    <PackageVersion Include="Microsoft.SemanticKernel.Plugins.Web" Version="1.60.0-alpha" />
    <!-- GitHub -->
    <PackageVersion Include="GitHub.Octokit.SDK" Version="0.0.31" />
  </ItemGroup>
</Project>
