<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <SelfContained>false</SelfContained>
    <PublishReadyToRun>true</PublishReadyToRun>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DataCollection.Infrastructure\DataCollection.Infrastructure.csproj" />
    <ProjectReference Include="..\DataCollection.Application\DataCollection.Application.csproj" />
    <ProjectReference Include="..\DataCollection.Common\DataCollection.Common.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.OpenAI" />
    <PackageReference Include="Pythonnet" />
    <PackageReference Include="MinimalHttpLogger" />
    <PackageReference Include="ConsoleAppFramework">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Serilog.Extensions.Hosting" />
    <PackageReference Include="Spectre.Console" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="appsettings.local.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
